#!/bin/bash

# a few things i would want to install after finishing installing my system

# packages orders:
#
# A-F
# G-L
# M-R
# S-Z

# some things to consider:
# intel-ucode will be installed, so remember to run `sudo grub-mkconfig -o /boot/grub/grub.cfg`
# and tlp will be as well, so enable/start it (tlp.service)

sudo pacman -S aria2 dmenu dunst fcitx5 fcitx5-mozc feh ffmpeg \
    gufw intel-ucode keepassxc libsixel \
    mpd mpv nnn numlockx network-manager-applet neovim openbox pandoc pavucontrol picom pulseaudio pulseaudio-alsa pulsemixer redshift rofi \
    scrot sxiv tint2 tlp thunar ttf-joypixels ttf-liberation wine w3m xsettingsd yt-dlp zathura zathura-pdf-mupdf zsh

# yay -S obconf ttf-symbola ttf-vlgothic hypnotix betterlockscreen
