#! /bin/sh

bspc monitor -d 一 二 三 ゲーム 勉強 音楽 &
# bspc monitor -d 001 010 011 100 101 110

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color "#ffffff"
bspc config normal_border_color  "#343434"
bspc config active_border_color  "#8375bc"

bspc rule -r *:*
bspc rule -a firefox:Toolkit:Picture-in-Picture focus=off state=floating border=off sticky=on layer=above
bspc rule -a firefox:Places focus=off state=floating sticky=on
bspc rule -a 'firefox:firefox:Save Image' state=floating sticky=on
bspc rule -a keepassxc state=floating follow=on focus=on
bspc rule -a mpv state=floating follow=on focus=on center=on
bspc rule -a MEGAsync state=floating follow=on focus=on border=off
bspc rule -a Nsxiv state=floating follow=on focus=on center=on
bspc rule -a polybar layer=above
bspc rule -a scrcpy state=floating
bspc rule -a tabbed focus=off
bspc rule -a Thunar state=floating follow=on focus=on
bspc rule -a firefox desktop='^1' follow=off focus=on
bspc rule -a discord desktop='^3' follow=off focus=off
bspc rule -a Steam:*:* desktop='^4' state=floating follow=off focus=on
bspc rule -a Anki desktop='^5' state=floating follow=on focus=on
bspc rule -a Pavucontrol desktop='^6' state=floating follow=on focus=on

(pkill sxhkd ; sxhkd) &
(pkill dunst ; dunst) &
(pkill megasync ; megasync) &
(pkill nm-applet ; nm-applet) &
${HOME}/.scripts/fehbg &
${HOME}/.scripts/welcome &
${HOME}/.config/polybar/launch.sh &
xsetroot -cursor_name left_ptr &

(pkill fcitx ; sleep 3s && fcitx5 || fcitx) &
(pkill xfce4-power-manager ; sleep 5s && xfce4-power-manager) &
(pkill xfce4-volumed ; sleep 5s && xfce4-volumed) &
(pkill redshift ; pkill -f "sleep 10s" ; sleep 10s && redshift) &
(pkill Discord ; pkill -f "sleep 2m 30s" ; sleep 2m 30s && discord --start-minimized) &
